server:
  port: 9000

spring:

  application:
    name: instagram_diana

  datasource:
    url: jdbc:mysql://instagram-server13.cums3cepciqy.ap-northeast-2.rds.amazonaws.com/instagram_server13?autoReconnect=true # 변경해주세요
    username: admin # 변경해주세요
    password: fkfkfk123 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


#server:
#  port: 9000
#  servlet:
#    context-path: /
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
#    username: kos
#    password: kos1234
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update #create update none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 658211206947-ephbghihhrh662n8ks32ijhlnnlk91dq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 2058319234361361 #2058319234361361 server13 production용 ID 511562584368297
            client-secret: 9eed5bfa7ac4425a0c141c4bf7f66273
            scope:
              - public_profile
              - email
#
#          naver:
#            client-id: smgzHgKqnDOVexvnukON
#            client-secret: xqKSvPC9Ty
#            scope:
#            - name
#            - email
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
#
#
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 return해줌.(value에는 getAttributes()한 값들이 들어가있음)